import Foundation
import SwiftData

@Model
final class Treatment: Identifiable {

    // MARK: - Identity
    var id: UUID
    var createdAt: Date

    // MARK: - Details
    var chemicalName: String
    var actionDescription: String

    /// Amount to add (e.g. "2.5")
    var amount: Double

    /// Unit string (e.g. "lbs", "oz", "cups", "gallons")
    var unit: String

    /// Stable product identity used for treatment substitutions and export.
    var productIdentifier: String?
    var globalPreferenceIdentifier: String?
    var calculatedDoseBeforeCap: Double = 0
    var calculatedDoseBeforeCapUnit: String = ""
    var wasDoseCapped: Bool = false

    /// Step-by-step instructions
    var instructions: String

    /// Urgency level mirrors ChemicalStatus
    var urgencyRaw: String

    // MARK: - Completion
    var isCompleted: Bool
    var completedAt: Date?
    var isSkipped: Bool = false
    var skippedAt: Date?
    var reminderNotificationIdentifier: String?
    var stepReminderNotificationIdentifier: String?
    var retestReminderNotificationIdentifier: String?
    /// Identifier of the targeted verification notification OWNED by a focused Check step.
    /// Migration-safe optional (defaults nil for legacy rows). Per the Check-owned verification model,
    /// the parent treatment establishes timing but the child Check owns the "retest X" notification.
    var checkReminderNotificationIdentifier: String?

    // MARK: - Source
    /// true = generated by Foundation Models / rule engine, false = manually added
    var isAIGenerated: Bool

    /// The parameter this treatment targets (e.g. "pH", "freeChlorine")
    var targetParameter: String

    /// Minutes to wait after completing THIS treatment before the next one is ready.
    /// 0 = no wait required. Used to schedule local notifications.
    var minutesBeforeNext: Int

    /// Display order within a treatment plan (lower = first)
    var sortOrder: Int

    // MARK: - Expected Effect
    var expectedEffectParameter: String = ""
    var expectedDelta: Double = 0
    var effectDelayHours: Int = 0
    var effectDurationHours: Int = 0
    var doNotRepeatBefore: Date?

    // MARK: - Adaptive Workflow
    var workflowStepKindRaw: String = TreatmentWorkflowStepKind.treatment.rawValue
    var checkParametersRaw: String = ""
    var parentTreatmentIDRaw: String?
    var checkResultTestIDRaw: String?
    var focusedCheckSummary: String?
    var workflowGeneration: Int = 0

    // MARK: - Relationship
    var poolTest: PoolTest?

    // MARK: - Init
    init(
        id: UUID = UUID(),
        createdAt: Date = Date(),
        chemicalName: String,
        actionDescription: String,
        amount: Double,
        unit: String,
        productIdentifier: String? = nil,
        globalPreferenceIdentifier: String? = nil,
        calculatedDoseBeforeCap: Double = 0,
        calculatedDoseBeforeCapUnit: String = "",
        wasDoseCapped: Bool = false,
        instructions: String,
        urgency: TreatmentUrgency = .recommended,
        isCompleted: Bool = false,
        completedAt: Date? = nil,
        isSkipped: Bool = false,
        skippedAt: Date? = nil,
        reminderNotificationIdentifier: String? = nil,
        stepReminderNotificationIdentifier: String? = nil,
        retestReminderNotificationIdentifier: String? = nil,
        isAIGenerated: Bool = true,
        targetParameter: String = "",
        minutesBeforeNext: Int = 0,
        sortOrder: Int = 0,
        expectedEffectParameter: String = "",
        expectedDelta: Double = 0,
        effectDelayHours: Int = 0,
        effectDurationHours: Int = 0,
        doNotRepeatBefore: Date? = nil,
        poolTest: PoolTest? = nil
    ) {
        self.id = id
        self.createdAt = createdAt
        self.chemicalName = chemicalName
        self.actionDescription = actionDescription
        self.amount = amount
        self.unit = unit
        self.productIdentifier = productIdentifier
        self.globalPreferenceIdentifier = globalPreferenceIdentifier
        self.calculatedDoseBeforeCap = calculatedDoseBeforeCap
        self.calculatedDoseBeforeCapUnit = calculatedDoseBeforeCapUnit
        self.wasDoseCapped = wasDoseCapped
        self.instructions = instructions
        self.urgencyRaw = urgency.rawValue
        self.isCompleted = isCompleted
        self.completedAt = completedAt
        self.isSkipped = isSkipped
        self.skippedAt = skippedAt
        self.reminderNotificationIdentifier = reminderNotificationIdentifier
        self.stepReminderNotificationIdentifier = stepReminderNotificationIdentifier
        self.retestReminderNotificationIdentifier = retestReminderNotificationIdentifier
        self.isAIGenerated = isAIGenerated
        self.targetParameter = targetParameter
        self.minutesBeforeNext = minutesBeforeNext
        self.sortOrder = sortOrder
        self.expectedEffectParameter = expectedEffectParameter
        self.expectedDelta = expectedDelta
        self.effectDelayHours = effectDelayHours
        self.effectDurationHours = effectDurationHours
        self.doNotRepeatBefore = doNotRepeatBefore
        self.poolTest = poolTest
    }

    var urgency: TreatmentUrgency {
        get { TreatmentUrgency(rawValue: urgencyRaw) ?? .recommended }
        set { urgencyRaw = newValue.rawValue }
    }
}

enum TreatmentWorkflowStepKind: String, Codable {
    case treatment
    case focusedCheck
}

// MARK: - Product Swap

/// Categories of swappable chemical products tied to a Treatment.
/// Used by the in-plan product picker; only categories with ≥2 options are listed.
enum ChemicalProductCategory: String, CaseIterable, Identifiable {
    case chlorine
    case pHIncreaser
    case pHDecreaser
    case stabilizer

    var id: String { rawValue }

    var sheetTitle: String {
        switch self {
        case .chlorine: return "Chlorine"
        case .pHIncreaser: return "pH Increaser"
        case .pHDecreaser: return "pH Decreaser"
        case .stabilizer: return "Stabilizer"
        }
    }

    func options(isSaltwater: Bool = false) -> [ChemicalProductID] {
        switch self {
        case .chlorine:
            return [.liquidChlorine10, .liquidChlorine12_5, .calHypoGranules, .dichlorGranules] + (isSaltwater ? [.saltGenerator] : [.trichlorTablets])
        case .pHIncreaser:
            return [.sodaAsh, .borax]
        case .pHDecreaser:
            return [.muriaticAcid31, .muriaticAcid20, .dryAcid]
        case .stabilizer:
            return [.granularCYA, .liquidStabilizer]
        }
    }

    func currentSelection(from config: PoolConfiguration) -> ChemicalProductID {
        switch self {
        case .chlorine: return config.chlorinePreference.productID
        case .pHIncreaser: return config.pHIncreaserPreference.productID
        case .pHDecreaser: return config.pHDecreaserPreference.productID
        case .stabilizer: return config.stabilizerPreference.productID
        }
    }

    func configApplying(selection: ChemicalProductID, to config: PoolConfiguration) -> PoolConfiguration {
        var updated = config
        switch self {
        case .chlorine:
            if let value = ChlorinePreference(rawValue: selection.rawValue) {
                updated.chlorinePreference = value
            }
        case .pHIncreaser:
            if let value = PHIncreaserPreference(rawValue: selection.rawValue) {
                updated.pHIncreaserPreference = value
            }
        case .pHDecreaser:
            if let value = PHDecreaserPreference(rawValue: selection.rawValue) {
                updated.pHDecreaserPreference = value
            }
        case .stabilizer:
            if let value = StabilizerPreference(rawValue: selection.rawValue) {
                updated.stabilizerPreference = value
            }
        }
        return updated
    }
}

extension Treatment {
    var workflowStepKind: TreatmentWorkflowStepKind {
        get { TreatmentWorkflowStepKind(rawValue: workflowStepKindRaw) ?? .treatment }
        set { workflowStepKindRaw = newValue.rawValue }
    }

    var isFocusedCheckStep: Bool {
        workflowStepKind == .focusedCheck
    }

    var checkParameters: [String] {
        get {
            checkParametersRaw
                .split(separator: ",")
                .map { String($0).trimmingCharacters(in: .whitespacesAndNewlines) }
                .filter { !$0.isEmpty }
        }
        set {
            checkParametersRaw = newValue.joined(separator: ",")
        }
    }

    var parentTreatmentID: UUID? {
        get { parentTreatmentIDRaw.flatMap(UUID.init(uuidString:)) }
        set { parentTreatmentIDRaw = newValue?.uuidString }
    }

    var checkResultTestID: UUID? {
        get { checkResultTestIDRaw.flatMap(UUID.init(uuidString:)) }
        set { checkResultTestIDRaw = newValue?.uuidString }
    }

    var isWatchlistItem: Bool {
        urgency == .advisory
    }

    var isAcidTreatment: Bool {
        let name = chemicalName.lowercased()
        return name.contains("muriatic acid")
            || name.contains("dry acid")
            || name.contains("ph decreaser")
            || (targetParameter == "pH" && expectedDelta < 0)
            || (targetParameter == "totalAlkalinity" && expectedDelta < 0 && name.contains("acid"))
    }

    /// Returns the swappable product category for this treatment, or nil when
    /// no alternative products exist (hardcoded treatments, visual indicators,
    /// or single-option categories like alkalinity / calcium increasers).
    var productCategory: ChemicalProductCategory? {
        if let productIdentifier, let productID = ChemicalProductID(rawValue: productIdentifier) {
            switch productID {
            case .saltGenerator, .liquidChlorine10, .liquidChlorine12_5, .trichlorTablets, .calHypoGranules, .dichlorGranules:
                return .chlorine
            case .sodaAsh, .borax:
                return .pHIncreaser
            case .muriaticAcid31, .muriaticAcid20, .dryAcid:
                return .pHDecreaser
            case .granularCYA, .liquidStabilizer:
                return .stabilizer
            case .bakingSoda, .calciumChloride:
                return nil
            }
        }
        switch targetParameter {
        case "freeChlorine":
            return ChlorinePreference.allCases.contains(where: { $0.displayName == chemicalName }) ? .chlorine : nil
        case "pH":
            if PHIncreaserPreference.allCases.contains(where: { $0.displayName == chemicalName }) {
                return .pHIncreaser
            }
            if PHDecreaserPreference.allCases.contains(where: { $0.displayName == chemicalName }) {
                return .pHDecreaser
            }
            return nil
        case "cyanuricAcid":
            return StabilizerPreference.allCases.contains(where: { $0.displayName == chemicalName }) ? .stabilizer : nil
        default:
            return nil
        }
    }
}

struct TreatmentTimingGuidance {
    static func cardTip(
        for treatment: Treatment,
        nextActionableTreatment: Treatment? = nil,
        requiresVerificationBeforeSwimming: Bool = false
    ) -> String? {
        compactCardTip(
            for: treatment,
            nextActionableTreatment: nextActionableTreatment,
            requiresVerificationBeforeSwimming: requiresVerificationBeforeSwimming
        )
    }

    static func requiresVerificationBeforeSwimming(for treatment: Treatment) -> Bool {
        if treatment.targetParameter == "pH" {
            guard let test = treatment.poolTest else { return treatment.urgency == .immediate }
            // Approved swim range is 7.0–7.8 inclusive (operating range 7.2–7.6). Only pH below 7.0 or above
            // 7.8 blocks swimming and requires verification; 7.0–7.8 is swim-safe.
            return !(7.0...7.8).contains(test.pH)
        }

        guard treatment.targetParameter == "freeChlorine" else { return false }
        if treatment.urgency == .immediate { return true }
        guard let test = treatment.poolTest else { return false }

        let indicators = Set(test.visualIndicators)
        let hasProblemWater = indicators.contains(VisualIndicator.cloudyWater.rawValue)
            || indicators.contains(VisualIndicator.greenWater.rawValue)
            || indicators.contains(VisualIndicator.algaeSpots.rawValue)
            || indicators.contains(VisualIndicator.strongChlorineSmell.rawValue)
            || test.waterClarityAssessment == .cloudy
            || test.visibleAlgaeAssessment == .present

        return hasProblemWater
            || test.combinedChlorine > 0.5
            || test.freeChlorine < ChemistryEngine().freeChlorineSwimReadinessMinimum(cyanuricAcid: test.cyanuricAcid)
    }

    /// Minutes to circulate before swimming after this treatment, when it imposes a swim wait. Returns nil
    /// when the treatment does not gate swimming (e.g. alkalinity/CYA/calcium maintenance adds, which do not
    /// require waiting to swim). Used to schedule the wait-complete "safe to swim" reminder on completion.
    static func swimWaitMinutes(for treatment: Treatment) -> Int? {
        guard treatment.amount > 0 else { return nil }
        switch treatment.targetParameter {
        case "freeChlorine":
            return 60
        case "pH":
            return 240
        case "totalAlkalinity":
            return treatment.isAcidTreatment ? 240 : nil
        default:
            return nil
        }
    }

    static func compactCardTip(
        for treatment: Treatment,
        nextActionableTreatment: Treatment? = nil,
        requiresVerificationBeforeSwimming: Bool = false
    ) -> String? {
        if
            let nextActionableTreatment,
            !nextActionableTreatment.isWatchlistItem,
            nextActionableTreatment.amount > 0,
            treatment.minutesBeforeNext > 0 {
            return compactWaitBeforeNextTreatmentTip(for: treatment, nextTreatment: nextActionableTreatment)
        }

        guard treatment.amount > 0 else { return nil }

        switch treatment.targetParameter {
        case "freeChlorine":
            return requiresVerificationBeforeSwimming ? "Test before swimming" : "Swim after ~1 hr"
        case "pH":
            return requiresVerificationBeforeSwimming ? "Test pH after ~4 hrs" : "Swim after ~4 hrs"
        case "totalAlkalinity":
            if treatment.isAcidTreatment {
                return requiresVerificationBeforeSwimming ? "Test after ~4 hrs" : "Swim after ~4 hrs"
            }
            return "Retest TA after 6-8 hrs"
        case "cyanuricAcid":
            return "Retest CYA after 24-48 hrs"
        default:
            return nil
        }
    }

    static func waitTimingText(for treatment: Treatment) -> String {
        timingGuidance(for: treatment) ?? "Use Next Pool Test timing."
    }

    static func timingGuidance(
        for treatment: Treatment,
        nextActionableTreatment: Treatment? = nil,
        requiresVerificationBeforeSwimming: Bool = false
    ) -> String? {
        if
            let nextActionableTreatment,
            !nextActionableTreatment.isWatchlistItem,
            nextActionableTreatment.amount > 0,
            treatment.minutesBeforeNext > 0 {
            return waitBeforeNextTreatmentTip(for: treatment, nextTreatment: nextActionableTreatment)
        }

        guard treatment.amount > 0 else { return nil }

        switch treatment.targetParameter {
        case "freeChlorine":
            if requiresVerificationBeforeSwimming {
                return "Test before swimming."
            }
            return "Circulate ~1 hr before swimming."
        case "pH":
            if requiresVerificationBeforeSwimming {
                return "Circulate ~4 hrs, then test pH before swimming."
            }
            return "Circulate ~4 hrs before swimming."
        case "totalAlkalinity":
            if treatment.isAcidTreatment {
                if requiresVerificationBeforeSwimming {
                    return "Circulate ~4 hrs, then test before swimming."
                }
                return "Circulate ~4 hrs before swimming."
            }
            return "Allow 6-8 hrs to circulate before retesting alkalinity or making another alkalinity adjustment."
        case "cyanuricAcid":
            return "Allow 24-48 hrs for CYA to register before retesting."
        default:
            return nil
        }
    }

    private static func compactWaitBeforeNextTreatmentTip(for treatment: Treatment, nextTreatment: Treatment) -> String {
        let wait = waitLabel(minutes: treatment.minutesBeforeNext)
        switch treatment.targetParameter {
        case "freeChlorine":
            return nextTreatment.isAcidTreatment
                ? "Wait \(wait) before acid"
                : "Wait \(wait) before next chemical"
        default:
            return "Wait \(wait) before next chemical"
        }
    }

    private static func waitBeforeNextTreatmentTip(for treatment: Treatment, nextTreatment: Treatment) -> String {
        let wait = waitLabel(minutes: treatment.minutesBeforeNext)
        switch treatment.targetParameter {
        case "freeChlorine":
            return nextTreatment.isAcidTreatment
                ? "Wait \(wait) before adding acid."
                : "Wait \(wait) before the next chemical."
        case "pH", "totalAlkalinity":
            return "Wait \(wait) before the next chemical."
        case "cyanuricAcid":
            return "Wait \(wait) before the next chemical."
        default:
            return "Wait \(wait) before the next chemical."
        }
    }

    private static func waitLabel(minutes: Int) -> String {
        if minutes < 60 {
            return "~\(minutes) min"
        }

        let hours = minutes / 60
        let remainingMinutes = minutes % 60

        if remainingMinutes == 0 {
            return "~\(hours) hr\(hours == 1 ? "" : "s")"
        }

        return "~\(hours) hr\(hours == 1 ? "" : "s") \(remainingMinutes) min"
    }
}

struct TreatmentPlanSummaryText {
    static func heroTitle(actionableTreatmentCount: Int) -> String {
        switch actionableTreatmentCount {
        case 0:
            return "No treatments today"
        case 1:
            return "1 treatment"
        default:
            return "\(actionableTreatmentCount) treatments"
        }
    }
}

struct WatchlistPresentationText {
    static func summary(count: Int) -> String {
        count == 1 ? "1 item to monitor" : "\(count) items to monitor"
    }

    static func shouldShow(count: Int) -> Bool {
        count > 0
    }
}

// MARK: - TreatmentUrgency

enum TreatmentUrgency: String, CaseIterable, Codable {
    case immediate   = "immediate"   // Critical — act now
    case recommended = "recommended" // Low/High — take action
    case optional    = "optional"    // Slightly off — minor adjustment
    case advisory    = "advisory"    // Monitor / avoid overcorrection

    var displayName: String {
        switch self {
        case .immediate:   return "Act Now"
        case .recommended: return "Recommended"
        case .optional:    return "Optional"
        case .advisory:    return "Advisory"
        }
    }

    var sortOrder: Int {
        switch self {
        case .immediate:   return 0
        case .recommended: return 1
        case .optional:    return 2
        case .advisory:    return 3
        }
    }
}
