import Foundation
import SwiftData

@Model
final class Treatment {

    // MARK: - Identity
    var id: UUID
    var createdAt: Date

    // MARK: - Details
    var chemicalName: String
    var actionDescription: String

    /// Amount to add (e.g. "2.5")
    var amount: Double

    /// Unit string (e.g. "lbs", "oz", "cups", "gallons")
    var unit: String

    /// Step-by-step instructions
    var instructions: String

    /// Urgency level mirrors ChemicalStatus
    var urgencyRaw: String

    // MARK: - Completion
    var isCompleted: Bool
    var completedAt: Date?

    // MARK: - Source
    /// true = generated by Foundation Models / rule engine, false = manually added
    var isAIGenerated: Bool

    /// The parameter this treatment targets (e.g. "pH", "freeChlorine")
    var targetParameter: String

    /// Minutes to wait after completing THIS treatment before the next one is ready.
    /// 0 = no wait required. Used to schedule local notifications.
    var minutesBeforeNext: Int

    /// Display order within a treatment plan (lower = first)
    var sortOrder: Int

    // MARK: - Relationship
    var poolTest: PoolTest?

    // MARK: - Init
    init(
        id: UUID = UUID(),
        createdAt: Date = Date(),
        chemicalName: String,
        actionDescription: String,
        amount: Double,
        unit: String,
        instructions: String,
        urgency: TreatmentUrgency = .recommended,
        isCompleted: Bool = false,
        completedAt: Date? = nil,
        isAIGenerated: Bool = true,
        targetParameter: String = "",
        minutesBeforeNext: Int = 0,
        sortOrder: Int = 0,
        poolTest: PoolTest? = nil
    ) {
        self.id = id
        self.createdAt = createdAt
        self.chemicalName = chemicalName
        self.actionDescription = actionDescription
        self.amount = amount
        self.unit = unit
        self.instructions = instructions
        self.urgencyRaw = urgency.rawValue
        self.isCompleted = isCompleted
        self.completedAt = completedAt
        self.isAIGenerated = isAIGenerated
        self.targetParameter = targetParameter
        self.minutesBeforeNext = minutesBeforeNext
        self.sortOrder = sortOrder
        self.poolTest = poolTest
    }

    var urgency: TreatmentUrgency {
        get { TreatmentUrgency(rawValue: urgencyRaw) ?? .recommended }
        set { urgencyRaw = newValue.rawValue }
    }
}

// MARK: - TreatmentUrgency

enum TreatmentUrgency: String, CaseIterable, Codable {
    case immediate   = "immediate"   // Critical — act now
    case recommended = "recommended" // Low/High — take action
    case optional    = "optional"    // Slightly off — minor adjustment

    var displayName: String {
        switch self {
        case .immediate:   return "Act Now"
        case .recommended: return "Recommended"
        case .optional:    return "Optional"
        }
    }

    var sortOrder: Int {
        switch self {
        case .immediate:   return 0
        case .recommended: return 1
        case .optional:    return 2
        }
    }
}
